version: '2'
services:

 freeradius:
  image: "freeradius/test_eap"
  ports:
   - "1812:1812/udp"
   - "1813:1813/udp"
   - "18120:18120"
  volumes:
   - "./clients.conf:/etc/raddb/clients.conf"
   - "pki:/etc/raddb/certs:ro"
  networks:
   mynet:
    ipv4_address: 172.26.0.100

networks:
  mynet:
    driver: bridge
    ipam:
      config:
      - subnet: 172.26.0.0/24

volumes:
  pki:
    external: true
